<?php
namespace App\Http\Controllers;
use App\Models\AccountingDocument;
use App\Models\FinancialPeriod;
use App\Models\JournalEntry;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class AccountingDocumentController extends Controller {
 public function index(Request $request){$q=AccountingDocument::with(['journalEntry','treasury','sourceAccount','destinationAccount'])->when($request->type,fn($x)=>$x->where('document_type',$request->type))->when($request->from,fn($x)=>$x->whereDate('document_date','>=',$request->from))->when($request->to,fn($x)=>$x->whereDate('document_date','<=',$request->to))->latest('document_date');return response()->json($q->paginate($request->integer('per_page',25)));}
 public function store(Request $request){$data=$request->validate(['document_type'=>'required|in:receipt,payment,transfer,opening_balance','document_date'=>'required|date','document_number'=>'nullable|string|max:80','amount'=>'required|numeric|gt:0','source_account_id'=>'required|exists:accounts,id','destination_account_id'=>'required|exists:accounts,id|different:source_account_id','treasury_id'=>'nullable|exists:treasuries,id','bank_id'=>'nullable|exists:banks,id','party_type'=>'nullable|string','party_id'=>'nullable|integer','payment_method'=>'nullable|string','reason'=>'required|string','notes'=>'nullable|string','branch_id'=>'nullable|exists:branches,id','fiscal_period_id'=>'nullable|exists:financial_periods,id']);$period=$data['fiscal_period_id']??FinancialPeriod::where('starts_on','<=',$data['document_date'])->where('ends_on','>=',$data['document_date'])->where('status','open')->value('id');if(!$period)throw ValidationException::withMessages(['document_date'=>'لا يوجد فترة مالية مفتوحة لهذا التاريخ.']);$doc=DB::transaction(function()use($data,$period){$doc=AccountingDocument::create(array_merge($data,['fiscal_period_id'=>$period,'document_number'=>$data['document_number']??('DOC-'.now()->format('YmdHis')),'created_by'=>auth()->id(),'status'=>'posted']));$entry=JournalEntry::create(['entry_date'=>$data['document_date'],'entry_number'=>$doc->document_number,'description_ar'=>$data['reason'],'description_en'=>$data['reason'],'status'=>'posted','fiscal_period_id'=>$period,'branch_id'=>$data['branch_id']??null,'posted_by'=>auth()->id(),'posted_at'=>now(),'source_type'=>AccountingDocument::class,'source_id'=>$doc->id,'treasury_id'=>$data['treasury_id']??null]);$entry->lines()->createMany([['account_id'=>$data['destination_account_id'],'debit'=>$data['amount'],'credit'=>0,'description'=>$data['reason']],['account_id'=>$data['source_account_id'],'debit'=>0,'credit'=>$data['amount'],'description'=>$data['reason']]]);$doc->update(['journal_entry_id'=>$entry->id]);return $doc->load('journalEntry');});return response()->json(['data'=>$doc],201);}
}
