<?php
namespace App\Http\Controllers;
use App\Models\CrmActivity;
use App\Models\Deal;
use App\Models\Lead;
use App\Models\PipelineStage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class CrmController extends Controller
{
    public function stages() { return response()->json(['data'=>PipelineStage::query()->orderBy('position')->withCount('deals')->get()]); }
    public function storeStage(Request $request) { $data=$request->validate(['name'=>'required|string|max:120','name_ar'=>'nullable|string|max:120','position'=>'nullable|integer|min:0','is_won'=>'boolean','is_lost'=>'boolean']); $stage=PipelineStage::create($data); activity()->performedOn($stage)->log('crm pipeline stage created'); return response()->json(['data'=>$stage],201); }
    public function updateStage(Request $request, PipelineStage $stage) { $stage->update($request->validate(['name'=>'sometimes|required|string|max:120','name_ar'=>'nullable|string|max:120','position'=>'nullable|integer|min:0','is_won'=>'boolean','is_lost'=>'boolean'])); activity()->performedOn($stage)->log('crm pipeline stage updated'); return response()->json(['data'=>$stage]); }
    public function leads(Request $request) { $query=Lead::query()->with(['customer','assignedTo'])->latest(); if($request->filled('status')) $query->where('status',$request->string('status')); return response()->json(['data'=>$query->paginate($request->integer('per_page',25))]); }
    public function storeLead(Request $request) { $lead=Lead::create($request->validate(['name'=>'required|string|max:160','company'=>'nullable|string|max:160','email'=>'nullable|email|max:160','phone'=>'nullable|string|max:40','source'=>'nullable|string|max:80','status'=>'nullable|string|max:40','assigned_to'=>'nullable|exists:admins,id','customer_id'=>'nullable|exists:customers,id'])); activity()->performedOn($lead)->log('crm lead created'); return response()->json(['data'=>$lead->load('customer')],201); }
    public function updateLead(Request $request, Lead $lead) { $lead->update($request->validate(['name'=>'sometimes|required|string|max:160','company'=>'nullable|string|max:160','email'=>'nullable|email|max:160','phone'=>'nullable|string|max:40','source'=>'nullable|string|max:80','status'=>'nullable|string|max:40','assigned_to'=>'nullable|exists:admins,id','customer_id'=>'nullable|exists:customers,id'])); activity()->performedOn($lead)->log('crm lead updated'); return response()->json(['data'=>$lead]); }
    public function deals(Request $request) { $query=Deal::query()->with(['stage','lead','customer','assignedTo'])->latest(); if($request->filled('pipeline_stage_id')) $query->where('pipeline_stage_id',$request->integer('pipeline_stage_id')); return response()->json(['data'=>$query->paginate($request->integer('per_page',50))]); }
    public function storeDeal(Request $request) { $deal=Deal::create($request->validate(['title'=>'required|string|max:180','value'=>'nullable|numeric|min:0','pipeline_stage_id'=>'required|exists:pipeline_stages,id','lead_id'=>'nullable|exists:leads,id','customer_id'=>'nullable|exists:customers,id','assigned_to'=>'nullable|exists:admins,id','expected_close_date'=>'nullable|date','notes'=>'nullable|string'])); activity()->performedOn($deal)->log('crm deal created'); return response()->json(['data'=>$deal->load('stage')],201); }
    public function moveDeal(Request $request, Deal $deal) { $data=$request->validate(['pipeline_stage_id'=>'required|exists:pipeline_stages,id']); $old=$deal->pipeline_stage_id; $deal->update($data); activity()->performedOn($deal)->withProperties(['from'=>$old,'to'=>$deal->pipeline_stage_id])->log('crm deal moved'); return response()->json(['data'=>$deal->load('stage')]); }
    public function activities(Request $request) { $query=CrmActivity::query()->with(['creator'])->latest('occurred_at'); foreach(['lead_id','deal_id','customer_id'] as $key) if($request->filled($key)) $query->where($key,$request->integer($key)); return response()->json(['data'=>$query->paginate($request->integer('per_page',50))]); }
    public function storeActivity(Request $request) { $data=$request->validate(['type'=>'required|string|max:40','body'=>'nullable|string','occurred_at'=>'nullable|date','lead_id'=>'nullable|exists:leads,id','deal_id'=>'nullable|exists:deals,id','customer_id'=>'nullable|exists:customers,id']); $data['created_by']=auth()->id(); $activity=CrmActivity::create($data); activity()->performedOn($activity)->log('crm activity created'); return response()->json(['data'=>$activity->load('creator')],201); }
    public function dashboard() { $stages=PipelineStage::query()->withCount('deals')->withSum('deals','value')->orderBy('position')->get(); $total=Deal::query()->count(); $won=Deal::query()->whereHas('stage',fn($q)=>$q->where('is_won',true))->count(); return response()->json(['data'=>['stages'=>$stages,'deals_count'=>$total,'conversion_rate'=>$total?round($won/$total*100,2):0,'pipeline_value'=>(float)Deal::query()->sum('value')]]); }
}
