<?php
namespace App\Http\Controllers;
use App\Models\Admin;
use App\Models\Employee;
use App\Models\Invoice;
use App\Models\SalesInvoice;
use App\Models\InvoiceTransferRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;
class InvoiceTransferRequestController extends Controller {
 public function index(Request $request){$actor=$request->user();$q=InvoiceTransferRequest::with(['fromEmployee:id,name','toEmployee:id,name','approver:id,name'])->latest();if($actor instanceof Employee&&!$actor->super_admin&&!str_contains(strtolower((string)$actor->role?->name),'admin'))$q->where(function($x)use($actor){$x->where('from_employee_id',$actor->id)->orWhere('to_employee_id',$actor->id);});return response()->json(['data'=>$q->paginate($request->integer('per_page',30))]);}
 public function store(Request $request){$actor=$request->user();abort_unless($actor instanceof Employee||$actor instanceof Admin,403);$data=$request->validate(['invoice_type'=>'required|in:pos,sales','invoice_id'=>'required|integer','to_employee_id'=>'required|exists:employees,id','from_employee_id'=>'nullable|exists:employees,id','note'=>'nullable|string|max:1000']);$model=$data['invoice_type']==='pos'?Invoice::findOrFail($data['invoice_id']):SalesInvoice::findOrFail($data['invoice_id']);$from=(int)($data['invoice_type']==='pos'?$model->cashier_id:$model->sales_representative?->employee_id);abort_unless(!$data['from_employee_id'] || (int)$data['from_employee_id']===$from,403,'لا يمكن تحويل فاتورة لا تخص مندوب المبيعات الذي سجل الدخول.');$shiftId=$data['invoice_type']==='pos'?$model->cashier_shift_id:null;abort_unless($from!== (int)$data['to_employee_id'],422,'لا يمكن تحويل الفاتورة لنفس البائع.');if($shiftId&&$model->shift?->status==='closed')return response()->json(['message'=>'لا يمكن تحويل فاتورة من وردية مغلقة.'],422);$requestModel=InvoiceTransferRequest::create(['invoice_type'=>$data['invoice_type'],'invoice_id'=>$model->id,'from_employee_id'=>$from?:null,'to_employee_id'=>$data['to_employee_id'],'cashier_shift_id'=>$shiftId,'note'=>$data['note']??null]);return response()->json(['data'=>$requestModel->load(['fromEmployee','toEmployee'])],Response::HTTP_CREATED);}
 public function approve(Request $request,InvoiceTransferRequest $transfer){$actor=$request->user();abort_unless($actor instanceof Admin&&($actor->super_admin||true),403,'اعتماد تحويل الفاتورة متاح للمدير فقط.');$data=$request->validate(['note'=>'nullable|string|max:1000']);$result=DB::transaction(function()use($transfer,$actor,$data){$transfer=InvoiceTransferRequest::lockForUpdate()->findOrFail($transfer->id);if($transfer->status!=='pending')abort(422,'تمت معالجة الطلب مسبقًا.');if($transfer->cashier_shift_id&&$transfer->shift?->status==='closed'){$transfer->update(['status'=>'cancelled','approved_by'=>$actor->id,'approved_at'=>now(),'note'=>$data['note']??$transfer->note]);return $transfer;}if($transfer->invoice_type==='pos'){$invoice=Invoice::lockForUpdate()->findOrFail($transfer->invoice_id);$invoice->update(['cashier_id'=>$transfer->to_employee_id]);}else{$invoice=SalesInvoice::lockForUpdate()->findOrFail($transfer->invoice_id);$rep=\App\Models\SalesRepresentative::where('employee_id',$transfer->to_employee_id)->first();if(!$rep)abort(422,'الموظف المستلم ليس مسجلًا كبائع.');$invoice->update(['sales_representative_id'=>$rep->id]);}$transfer->update(['status'=>'approved','approved_by'=>$actor->id,'approved_at'=>now(),'note'=>$data['note']??$transfer->note]);return $transfer;});return response()->json(['data'=>$result->load(['fromEmployee','toEmployee','approver'])]);}
 public function reject(Request $request,InvoiceTransferRequest $transfer){$actor=$request->user();abort_unless($actor instanceof Admin,403);$transfer->update(['status'=>'rejected','approved_by'=>$actor->id,'approved_at'=>now(),'note'=>$request->input('note',$transfer->note)]);return response()->json(['data'=>$transfer]);}
}
